### ISSUE TITLE
Components missed in demos

### ISSUE THREAD

**Issue by Gronfi** [mmarquee/DelphiWebDriver#2]
Hi, there are some components missing that belong to next units: AutomatedCombobox, AutomatedEdit, AutomatedStringGrid, AutomatedMaskEdit, AutomatedStaticText

Where can we find these units/components?

**Comment by mmarquee** [comment]
Hi,, these are from the 'https://github.com/markhumphreysjhc/DelphiUIAutomation' project. where I got the sample host from (so I can tell I get the same results via this as well as automation). However, I should refactor the code so it just uses standard Delphi components. I will do this tonite / tomorrow hopefully.

**Comment by mmarquee** [comment]
I've just finished off committing changes to remove the extra library, so it should work independantly

**Comment by mmarquee** [comment]
I'll close the issue
